---
apiVersion: v1
kind: Pod
metadata:
  name: shell-volumes
  labels:
    app: shell
spec:
  volumes:
    - name: tmp-data
      emptyDir: {}
    - name: data
      persistentVolumeClaim:
        claimName: volumen-pvc
  containers:
    - name: shell
      image: raelga/toolbox
      command: ["bash", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: "/data"
          name: data
        - mountPath: "/tmp-data"
          name: tmp-data
