apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-gatet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
      - name: cats
        image: raelga/cats:gatet