---
apiVersion: v1
kind: Pod
metadata:
  name: cats-gatet-pod-1
  labels:
    app: cats
spec:
  containers:
    - name: cats
      image: raelga/cats:gatet
---
apiVersion: v1
kind: Pod
metadata:
  name: cats-gatet-pod-2
  labels:
    app: cats
spec:
  containers:
    - name: cats
      image: raelga/cats:gatet
---
apiVersion: v1
kind: Pod
metadata:
  name: cats-gatet-pod-3
  labels:
    app: cats
spec:
  containers:
    - name: cats
      image: raelga/cats:gatet
---
apiVersion: v1
kind: Pod
metadata:
  name: cats-gatet-pod-4
  labels:
    app: cats
spec:
  containers:
    - name: cats
      image: raelga/cats:gatet
---
apiVersion: v1
kind: Pod
metadata:
  name: cats-gatet-pod-5
  labels:
    app: cats
spec:
  containers:
    - name: cats
      image: raelga/cats:gatet