---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-broad
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
      - name: cats
        image: raelga/cats:gatet
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: "1"
            memory: 100Mi
