---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-also
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: app
        image: raelga/cats:liam
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: "1"
            memory: 100Mi
