---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-liam
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cats
      cat: liam
  template:
    metadata:
      labels:
        app: cats
        cat: liam
    spec:
      containers:
      - name: cats
        image: raelga/cats:liam
