---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-nocolor
  labels:
    app: cats
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cats
    matchExpressions:
      - { key: cat, operator: DoesNotExist }
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
      - name: cats
        image: raelga/cats:gatet
