---
apiVersion: v1
kind: Pod
metadata:
  name: cats-lia-pod-1
  labels:
    app: cats
    cat: lia
spec:
  containers:
    - name: cats
      image: raelga/cats:lia
---
apiVersion: v1
kind: Pod
metadata:
  name: cats-lia-pod-2
  labels:
    app: cats
    cat: lia
spec:
  containers:
    - name: cats
      image: raelga/cats:lia
---
apiVersion: v1
kind: Pod
metadata:
  name: cats-lia-pod-3
  labels:
    app: cats
    cat: lia
spec:
  containers:
    - name: cats
      image: raelga/cats:lia