---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-lia
spec:
  replicas: 6
  selector:
    matchLabels:
      app: cats
      cat: lia
  template:
    metadata:
      labels:
        app: cats
        cat: lia
    spec:
      containers:
      - name: cats
        image: raelga/cats:lia
