apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: probes
  labels:
    app: probes
spec:
  replicas: 8
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
      - name: app
        image: raelga/cats:neu
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /bad-endpoint
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2