---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis-master
          image: redis:3.2
          imagePullPolicy: Always
          ports:
            - name: redis-server
              containerPort: 6379
          resources:
            limits:
              memory: 128M
              cpu: 200m
            requests:
              memory: 128M
              cpu: 200m
