apiVersion: v1
clusters:
- cluster:
    server: localhost:8080
  name: localhost
contexts:
- context:
    cluster: localhost
    user: ""
  name: localhost
current-context: localhost
kind: Config
preferences: {}
users: []