---
apiVersion: v1
kind: Pod
metadata:
  name: shell-api
  annotations:
    build: v1.0.1
    builder: rael
  labels:
    app: shell
spec:
  containers:
    - name: shell
      image: raelga/toolbox
      command: ["bash", "-c", "sleep 3600"]
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: podinfo
          mountPath: /etc/api-info
          readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
