---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook
          image: raelga/guestbook:latest
          ports:
            - name: http-server
              containerPort: 3000
          resources:
            limits:
              memory: 128M
              cpu: 50m
            requests:
              memory: 128M
              cpu: 50m
---
kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis-master
          image: redis:3.2
          imagePullPolicy: Always
          ports:
            - name: redis-server
              containerPort: 6379
          resources:
            limits:
              memory: 128M
              cpu: 200m
            requests:
              memory: 128M
              cpu: 200m
---
kind: Service
apiVersion: v1
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
        - name: redis-slave
          image: ibmcom/guestbook-redis-slave:v2
          ports:
            - name: redis-server
              containerPort: 6379
          resources:
            limits:
              memory: 128M
              cpu: 200m
            requests:
              memory: 128M
              cpu: 200m
---
kind: Service
apiVersion: v1
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    app: redis
    role: slave
