---
apiVersion: v1
kind: Pod
metadata:
  name: shell-secret
  labels:
    app: shell
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-config
  containers:
    - name: shell
      image: raelga/toolbox
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: secret-key
      command: ["bash", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "25m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1024Mi"
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
