---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-and-shell-volume
  labels:
    app: nginx
    tier: frontend
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx:1.15.11-alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: shell
    image: raelga/toolbox
    command: ['bash', '-c', 'sleep 3600']
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
    volumeMounts:
    - name: html
      mountPath: /html