apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: my-app
    version: v1.0.0