---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-resources-0
  labels:
    app: busybox
    resources: both
    id: "0"
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 321']
    resources:
      requests:
        cpu: "25m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1024Mi"