---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-resources-requests-unschedulable
  labels:
    app: busybox
    resources: unschedulable
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 321']
    resources:
      requests:
        cpu: "4"
        memory: "1000Mi"