---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-resources-limits
  labels:
    app: busybox
    resources: limits
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 321']
    resources:
      limits:
        cpu: "100m"
        memory: "100Mi"