apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../bases

patches:
  - target:
      version: v1
      kind: Service
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
