apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  labels:
    app: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: hello
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello
              image: ubuntu:trusty
              env:
                - name: JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['job-name']
              command:
                - /bin/sh
              args:
                - -c
                - >-
                  echo "Hello, I was created by the Job ${JOB_NAME} from a CronJob and ran in $(hostname) at $(date)."
              resources:
                requests:
                  cpu: 10m
                  memory: 32M
                limits:
                  cpu: 10m
                  memory: 32M
