---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-0
  labels:
    app: busybox
    id: "0"
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 321']
