---
apiVersion: v1
kind: Pod
metadata:
  name: hello-sh
  labels:
    app: hello-sh
spec:
  containers:
  - name: hello-sh
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes from $(hostname)! && sleep 3600']
