apiVersion: v1
clusters:
- cluster:
    server: <endpoint-url>
    certificate-authority-data: <base64-encoded-ca-cert>
  name: <cluster-name>
contexts:
- context:
    cluster: <cluster-name>
    user: k8s
  name: <cluster-name>.talks.aws.rael.io
kind: Config
preferences: {}
users:
- name: k8s
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
      env:
        - name: AWS_PROFILE
          value: "k8s-talks"