apiVersion: v1
kind: Pod
metadata:
  name: busybox-init-containers
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo The app is running! && sleep 15 && touch /tmp/healthy && sleep 3600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 15
      periodSeconds: 1
  initContainers:
  - name: init-dummy-svc-wait
    image: bash
    command: 
    - sh
    - -c
    - until nslookup dummy-svc; do echo waiting for dummy-svc; sleep 2; done;
  - name: init-gcloud-sdk
    image: google/cloud-sdk:245.0.0-alpine