apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-affinity
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hostname-affinity
  template:
    metadata:
      labels:
        app: hostname-affinity
    spec:
      containers:
        - name: hostname
          image: ubuntu:trusty
          env:
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          command:
            - /bin/sh
          args:
            - -c
            - >-
              while [ true ]; do
              echo "${APP_NAME} app deployment running on $(hostname)" ;
              sleep 10 ;
              done
          resources:
            requests:
              cpu: 10m
              memory: 32M
            limits:
              cpu: 10m
              memory: 32M
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: hostname-affinity
                topologyKey: "kubernetes.io/hostname"
